-------------------- ADDRESS_TYPE
INSERT INTO ADDRESS_TYPE (ADDRESS_TYPE_DESC) VALUES ('Mailing');
INSERT INTO ADDRESS_TYPE (ADDRESS_TYPE_DESC) VALUES ('Home');
INSERT INTO ADDRESS_TYPE (ADDRESS_TYPE_DESC) VALUES ('Work');

-------------------- CONTACT_TYPE
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_DESC) VALUES ('ONR');
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_DESC) VALUES ('DCAA');
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_DESC) VALUES ('DFAS');

-- ------------------EMAIL_TYPE
INSERT INTO EMAIL_TYPE (EMAIL_TYPE_DESC) VALUES ('Work');
INSERT INTO EMAIL_TYPE (EMAIL_TYPE_DESC) VALUES ('Personal');

-- ------------------PHONE_TYPE
INSERT INTO PHONE_TYPE (PHONE_TYPE_DESC) VALUES ('Work');
INSERT INTO PHONE_TYPE (PHONE_TYPE_DESC) VALUES ('Personal');
INSERT INTO PHONE_TYPE (PHONE_TYPE_DESC) VALUES ('fax');

------------------- OFFICE_TYPE
INSERT INTO OFFICE_TYPE (OFFICE_TYPE_DESC) VALUES ('HQ');